[package]
name = "highflowey/flowuiframework"
version = "0.0.3"
registry = "https://github.com/UpliftGames/wally-index"
description = "Inspired by fusion"
realm = "shared"

[dependencies]
signal = "sleitnick/signal@1.5.0"